Feat: crvYfiEth smart solver
yearn/hardhat-monorepo pull request #117
Opened 2022-02-25 14:40 UTC by gotzenx

Now solver can execute even if only one token is ready to be swapped, and use the correct `execute` method on TF contract for gas optimization.

2022-02-28 14:51 UTC, b0dhidharma requested changes
Other than the suggested changes this is 10/10. Great f* work !

2022-02-28 14:51 UTC, b0dhidharma commented on packages/yswaps/scripts/libraries/solvers/multicall/CurveYfiEth.ts
> +    const shouldExecuteCrvTrade = (await this._crv.balanceOf(strategy)).gt(DUST_THRESHOLD);
```suggestion
    const shouldExecuteCrvTrade = crvBalance.gt(DUST_THRESHOLD);
```

2022-02-28 14:51 UTC, b0dhidharma commented on packages/yswaps/scripts/libraries/solvers/multicall/CurveYfiEth.ts
> +    const shouldExecuteCvxTrade = (await this._cvx.balanceOf(strategy)).gt(DUST_THRESHOLD);
```suggestion
    const shouldExecuteCvxTrade = cvxBalance.gt(DUST_THRESHOLD);
```

2022-02-28 15:30 UTC, poolpitako approved these changes
This refactors looks good. At a certain point we should abstract some of the logic and apply to the other trade which is almost the same: spell/eth.

2022-02-28 15:30 UTC, poolpitako commented on packages/yswaps/scripts/libraries/solvers/multicall/CurveYfiEth.ts
> +    const shouldExecuteCvxTrade = cvxBalance.gt(DUST_THRESHOLD);
I don't know if it makes sense to execute these trades separately.
Perhaps something like:
```
cvxBalance.gt(DUST_THRESHOLD) || crvBalance.gt(DUST_THRESHOLD)
```

makes more sense

2022-03-01 11:39 UTC, poolpitako commented on packages/yswaps/scripts/libraries/solvers/multicall/CurveYfiEth.ts
> +    const shouldExecuteCvxTrade = cvxBalance.gt(DUST_THRESHOLD);
they should increase together since it's a convex strat.

2022-03-02 13:19 UTC, merged